Models/VehicleModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MonoTest.MVC.Models
{
    public class VehicleModel
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Abrv { get; set; }

        [ForeignKey("VehicleMake")]
        public int MakeId { get; set; }
        public VehicleMake VehicleMake { get; set; }
    }
}

Controllers/VehicleModelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MonoTest.MVC.DAL;
using MonoTest.MVC.Models;
using AutoMapper;
using MonoTest.MVC.AutoMapper;
using MonoTest.MVC.Models.ViewModels;
using System.Data.SqlClient;
using System.Security.Cryptography;
using PagedList;

namespace MonoTest.MVC.Controllers
{
    public class VehicleModelController : Controller
    {
        private VehicleContext db = new VehicleContext();
        private Mapper mapper = AutoMapperConfig.GetMapper();

        private List<VehicleModelVM> MapVehicleModels(List<VehicleModel> models)
        {
            List<VehicleModelVM> modelsVM = new List<VehicleModelVM>();
            foreach (VehicleModel model in models)
            {
                modelsVM.Add(MapVehicleModel(model));
            }
            return modelsVM;
        }

        private VehicleModelVM MapVehicleModel(VehicleModel model)
        {
            return mapper.Map<VehicleModelVM>(model);
        }

        // GET: VehicleModel
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string currentFilterByMake, string searchString, string searchStringByMake, int? page)
        {
            ViewBag.CurrentSortModel = sortOrder;
            ViewBag.NameSortParmModel = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.AbrvSortParmModel = (sortOrder == "abrv") ? "abrv_desc" : "abrv";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            if (searchStringByMake != null)
            {
                page = 1;
            }
            else
            {
                searchStringByMake = currentFilterByMake;
            }

            ViewBag.CurrentFilterModel = searchString;
            ViewBag.CurrentFilterModelByMake = searchStringByMake;

            var models = db.VehicleModels.AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                models = models.Where(m => m.Name.Contains(searchString)
                                       || m.Abrv.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(searchStringByMake))
            {
                var makes = db.VehicleMakes.Where(m => m.Name.Contains(searchStringByMake)
                                        || m.Abrv.Contains(searchStringByMake)).ToList();
                var makeIds = makes.Select(m => m.Id).ToList();

                models = models.Where(m => makeIds.Contains(m.MakeId));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    models = models.OrderByDescending(m => m.Name);
                    break;
                case "abrv":
                    models = models.OrderBy(m => m.Abrv);
                    break;
                case "abrv_desc":
                    models = models.OrderByDescending(m => m.Abrv);
                    break;
                default:
                    models = models.OrderBy(m => m.Name);
                    break;
            }
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            var vehicleModels = MapVehicleModels(models.ToList()).ToPagedList(pageNumber,pageSize);

            return View(vehicleModels);
            
        }

        // GET: VehicleModel/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleModel vehicleModel = await db.VehicleModels.FindAsync(id);
            if (vehicleModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleMakeName = (await db.VehicleMakes.FindAsync(vehicleModel.MakeId)).Name;
            return View(MapVehicleModel(vehicleModel));
        }

        // GET: VehicleModel/Create
        public ActionResult Create()
        {
            ViewBag.MakeId = new SelectList(db.VehicleMakes, "Id", "Name");
            return View();
        }

        // POST: VehicleModel/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name,Abrv,MakeId")] VehicleModel vehicleModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.VehicleModels.Add(vehicleModel);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.ToString());
            }
            

            ViewBag.MakeId = new SelectList(db.VehicleMakes, "Id", "Name", vehicleModel.MakeId);
            return View(MapVehicleModel(vehicleModel));
        }

        // GET: VehicleModel/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleModel vehicleModel = await db.VehicleModels.FindAsync(id);
            if (vehicleModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.MakeId = new SelectList(db.VehicleMakes, "Id", "Name", vehicleModel.MakeId);
            return View(MapVehicleModel(vehicleModel));
        }

        // POST: VehicleModel/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Abrv,MakeId")] VehicleModel vehicleModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicleModel).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.MakeId = new SelectList(db.VehicleMakes, "Id", "Name", vehicleModel.MakeId);
            return View(MapVehicleModel(vehicleModel));
        }

        // GET: VehicleModel/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleModel vehicleModel = await db.VehicleModels.FindAsync(id);
            if (vehicleModel == null)
            {
                return HttpNotFound();
            }
            return View(MapVehicleModel(vehicleModel));
        }

        // POST: VehicleModel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                VehicleModel vehicleModel = await db.VehicleModels.FindAsync(id);
                db.VehicleModels.Remove(vehicleModel);
                await db.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, ex.ToString());
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/VehicleModel/Create.cshtml
@model MonoTest.MVC.Models.ViewModels.VehicleModelVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehicleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MakeId, "MakeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MakeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MakeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/VehicleModel/Delete.cshtml
@model MonoTest.MVC.Models.ViewModels.VehicleModelVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehicleModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VehicleMake.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleMake.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abrv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/VehicleModel/Details.cshtml
@model MonoTest.MVC.Models.ViewModels.VehicleModelVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VehicleModel</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abrv)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            Vehicle make
        </dt>

        <dd>
            @ViewBag.VehicleMakeName
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/VehicleModel/Edit.cshtml
@model MonoTest.MVC.Models.ViewModels.VehicleModelVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehicleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MakeId, "MakeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MakeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MakeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/VehicleModel/Index.cshtml
@model PagedList.IPagedList<MonoTest.MVC.Models.ViewModels.VehicleModelVM>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "VehicleModels";
}

<h2>VehicleModels</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "VehicleModel", FormMethod.Get))
{
    <p>
        Search by name or abrv: @Html.TextBox("SearchString", ViewBag.CurrentFilterModel as string)
        &nbsp
        Search by make: @Html.TextBox("SearchStringByMake", ViewBag.CurrentFilterModelByMake as string)
        <input type="submit" value="Search" />
    </p>

    <p>
        
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParmModel, currentFilter = ViewBag.CurrentFilterModel, currentFilterByMake= ViewBag.CurrentFilterModelByMake })
        </th>
        <th>
            @Html.ActionLink("Abrv", "Index", new { sortOrder = ViewBag.AbrvSortParmModel, currentFilter = ViewBag.CurrentFilterModel, currentFilterByMake = ViewBag.CurrentFilterModelByMake })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Abrv)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSortModel, currentFilter = ViewBag.CurrentFilterModel , currentFilterByMake = ViewBag.CurrentFilterModelByMake }))